### ISSUE TITLE
报错无法启动

### ISSUE THREAD

**Issue by liuyuhang9066** [GroupMountain/GMLIB-LegacyRemoteCallApi#14]
插件报错，无法启动
LeviLamina版本：0.9.3
GMLIB版本：0.9.4
01:32:34.256 INFO [PreLoader] Loading symbols from pdb...
01:32:50.064 INFO [PreLoader] Loaded 597772 symbols
01:32:50.103 INFO [PreLoader] Loading Reverse Lookup Table
01:32:51.344 INFO [PreLoader] LeviLamina.dll Loaded.
01:32:51.492 INFO [LeviLamina] 统计已启用，您可以在配置文件中禁用统计
01:32:51.567 INFO [CrashLogger] 已成功启用崩溃记录器
01:32:51.567 INFO [LeviLamina]
01:32:51.567 INFO [LeviLamina]          _               _ _                    _
01:32:51.567 INFO [LeviLamina]         | |    _____   _(_) |    __ _ _ __ ___ (_)_ __   __ _
01:32:51.567 INFO [LeviLamina]         | |   / _ \ \ / / | |   / _` | '_ ` _ \| | '_ \ / _` |
01:32:51.567 INFO [LeviLamina]         | |__|  __/\ V /| | |__| (_| | | | | | | | | | | (_| |
01:32:51.567 INFO [LeviLamina]         |_____\___| \_/ |_|_____\__,_|_| |_| |_|_|_| |_|\__,_|
01:32:51.567 INFO [LeviLamina]
01:32:51.567 INFO [LeviLamina]         --------   Light-Weight BDS Plugin Loader   ----------
01:32:51.567 INFO [LeviLamina]
01:32:51.567 INFO [LeviLamina]
01:32:51.567 INFO [LeviLamina] LeviLamina 是一个由 LGPLv3 授权的自由软件
01:32:51.567 INFO [LeviLamina] 帮助我们翻译和改进文本 -> https://translate.liteldev.com/
01:32:51.680 INFO [LeviLamina] 正在加载插件...
01:32:51.689 INFO [LegacyMoney] Loaded!
01:32:51.700 INFO [LeviLamina] LegacyMoney 已加载
01:32:51.958 INFO [LegacyParticleAPI] Loaded
01:32:51.959 INFO [LeviLamina] LegacyParticleAPI 已加载

         ________  _____ ______   ___       ___  ________
        |\   ____\|\   _ \  _   \|\  \     |\  \|\   __  \
        \ \  \___|\ \  \\\__\ \  \ \  \    \ \  \ \  \|\ /_
         \ \  \  __\ \  \\|__| \  \ \  \    \ \  \ \   __  \
          \ \  \|\  \ \  \    \ \  \ \  \____\ \  \ \  \|\  \
           \ \_______\ \__\    \ \__\ \_______\ \__\ \_______\
            \|_______|\|__|     \|__|\|_______|\|__|\|_______|

           ------------  Group Mountain Library  ------------

01:32:52.858 INFO [GMLIB] Loaded Version: LeviLamina-0.9.3 with GMLIB-0.9.4
01:32:52.858 INFO [GMLIB] GMLIB is a free library for LeviLamina licensed under LGPLv3
01:32:52.858 INFO [GMLIB] Author: GroupMountain
01:32:52.858 INFO [GMLIB] Repository: https://github.com/GroupMountain/GMLIB
01:32:52.860 INFO [LeviLamina] GMLIB 已加载
01:32:52.863 INFO [LegacyRemoteCall] loading...
01:32:52.863 INFO [LeviLamina] LegacyRemoteCall 已加载
01:32:52.880 INFO [LeviLamina] DeathMessages 已加载
01:32:52.884 ERROR [LeviLamina] C++ Exception: std::system_error, from <LeviLamina>:
01:32:52.884 ERROR [LeviLamina] [0x0000007F:system] 找不到指定的程序。
01:33:18.763 ERROR [LeviLamina] Dependency diagnostic:
   module: D:\EQ\eq\qsfser\BDS\plugins\GMLIB-LegacyRemoteCallApi\GMLIB-LegacyRemoteCallApi.dll
   missing procedure:
   |- GMLIB.dll
   |---- ?setSpawnPoint@GMLIB_Player@@QEAAXVBlockPos@@V?$AutomaticID@VDimension@@H@@@Z
   |     public: void __cdecl GMLIB_Player::setSpawnPoint(class BlockPos, class AutomaticID<class Dimension, int>)
   |---- ?getDamageSource@DeathMessageAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAVActorDamageSource@@XZ
   |     public: class ActorDamageSource & __cdecl GMLIB::Event::EntityEvent::DeathMessageAfterEvent::getDamageSource(void) const
   |---- ?registerFurnaceRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VRecipeIngredient@@1V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@V?$variant@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@2@@5@@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerFurnaceRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class RecipeIngredient, class RecipeIngredient, class std::vector<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::allocator<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>>, class std::variant<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>>)
   |---- ?getRainingLastTick@WeatherUpdateBeforeEvent@LevelEvent@Event@GMLIB@@QEBAAEAHXZ
   |     public: int & __cdecl GMLIB::Event::LevelEvent::WeatherUpdateBeforeEvent::getRainingLastTick(void) const
   |---- ?getItem@ItemActorSpawnBeforeEvent@EntityEvent@Event@GMLIB@@QEBAAEAVItemStack@@XZ
   |     public: class ItemStack & __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnBeforeEvent::getItem(void) const
   |---- ?getBlockSource@ItemActorSpawnBeforeEvent@EntityEvent@Event@GMLIB@@QEBAAEAVBlockSource@@XZ
   |     public: class BlockSource & __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnBeforeEvent::getBlockSource(void) const
   |---- ?resetScore@GMLIB_Scoreboard@@QEAA_NUActorUniqueID@@_N@Z
   |     public: bool __cdecl GMLIB_Scoreboard::resetScore(struct ActorUniqueID, bool)
   |---- ?getDamage@MobHurtAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAMXZ
   |     public: float & __cdecl GMLIB::Event::EntityEvent::MobHurtAfterEvent::getDamage(void) const
   |---- ?clearSpawnPoint@GMLIB_Player@@QEAAXXZ
   |     public: void __cdecl GMLIB_Player::clearSpawnPoint(void)
   |---- ?getSpawner@ItemActorSpawnBeforeEvent@EntityEvent@Event@GMLIB@@QEBA?AV?$optional_ref@VActor@@@@XZ
   |     public: class optional_ref<class Actor> __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnBeforeEvent::getSpawner(void) const
   |---- ?getToDimensionId@ActorChangeDimensionBeforeEvent@EntityEvent@Event@GMLIB@@QEBAAEAV?$AutomaticID@VDimension@@H@@XZ
   |     public: class AutomaticID<class Dimension, int> & __cdecl GMLIB::Event::EntityEvent::ActorChangeDimensionBeforeEvent::getToDimensionId(void) const
   |---- ?getInstance@GMLIB_Level@@SAPEAV1@XZ
   |     public: static class GMLIB_Level * __cdecl GMLIB_Level::getInstance(void)
   |---- ?getWorldSpawn@GMLIB_Level@@QEAA?AVBlockPos@@XZ
   |     public: class BlockPos __cdecl GMLIB_Level::getWorldSpawn(void)
   |---- ?setObjectiveDisplay@GMLIB_Scoreboard@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0W4ObjectiveSortOrder@@@Z
   |     public: void __cdecl GMLIB_Scoreboard::setObjectiveDisplay(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, enum ObjectiveSortOrder)
   |---- ?setWorldSpawn@GMLIB_Level@@QEAAXVBlockPos@@@Z
   |     public: void __cdecl GMLIB_Level::setWorldSpawn(class BlockPos)
   |---- ?getAllUuids@GMLIB_Player@@SA?AV?$vector@VUUID@mce@@V?$allocator@VUUID@mce@@@std@@@std@@_N@Z
   |     public: static class std::vector<class mce::UUID, class std::allocator<class mce::UUID>> __cdecl GMLIB_Player::getAllUuids(bool)
   |---- ?getAllFakePlayers@GMLIB_Scoreboard@@QEAA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@XZ
   |     public: class std::vector<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::allocator<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>> __cdecl GMLIB_Scoreboard::getAllFakePlayers(void)
   |---- ?getDeathMessage@DeathMessageAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAU?$pair@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@XZ
   |     public: struct std::pair<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::allocator<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>>> & __cdecl GMLIB::Event::EntityEvent::DeathMessageAfterEvent::getDeathMessage(void) const
   |---- ?setScore@GMLIB_Scoreboard@@QEAA?AV?$optional@H@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@UActorUniqueID@@HW4PlayerScoreSetFunction@@_N@Z
   |     public: class std::optional<int> __cdecl GMLIB_Scoreboard::setScore(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, struct ActorUniqueID, int, enum PlayerScoreSetFunction, bool)
   |---- ?getPosition@ItemActorSpawnBeforeEvent@EntityEvent@Event@GMLIB@@QEBAAEAVVec3@@XZ
   |     public: class Vec3 & __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnBeforeEvent::getPosition(void) const
   |---- ?getLightningLastTick@WeatherUpdateBeforeEvent@LevelEvent@Event@GMLIB@@QEBAAEAHXZ
   |     public: int & __cdecl GMLIB::Event::LevelEvent::WeatherUpdateBeforeEvent::getLightningLastTick(void) const
   |---- ?setPlayerNbt@GMLIB_Player@@SA_NAEBVUUID@mce@@AEAVCompoundTag@@_N@Z
   |     public: static bool __cdecl GMLIB_Player::setPlayerNbt(class mce::UUID const &, class CompoundTag &, bool)
   |---- ?getSpawnPoint@GMLIB_Player@@QEAA?AU?$pair@VBlockPos@@V?$AutomaticID@VDimension@@H@@@std@@XZ
   |     public: struct std::pair<class BlockPos, class AutomaticID<class Dimension, int>> __cdecl GMLIB_Player::getSpawnPoint(void)
   |---- ?getSpawner@ItemActorSpawnAfterEvent@EntityEvent@Event@GMLIB@@QEBA?AV?$optional_ref@VActor@@@@XZ
   |     public: class optional_ref<class Actor> __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnAfterEvent::getSpawner(void) const
   |---- ?resetScore@GMLIB_Scoreboard@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UActorUniqueID@@_N@Z
   |     public: bool __cdecl GMLIB_Scoreboard::resetScore(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, struct ActorUniqueID, bool)
   |---- ?getAllEntities@GMLIB_Scoreboard@@QEAA?AV?$vector@UActorUniqueID@@V?$allocator@UActorUniqueID@@@std@@@std@@XZ
   |     public: class std::vector<struct ActorUniqueID, class std::allocator<struct ActorUniqueID>> __cdecl GMLIB_Scoreboard::getAllEntities(void)
   |---- ?getInstance@GMLIB_Scoreboard@@SAPEAV1@XZ
   |     public: static class GMLIB_Scoreboard * __cdecl GMLIB_Scoreboard::getInstance(void)
   |---- ?getRainLevel@WeatherUpdateBeforeEvent@LevelEvent@Event@GMLIB@@QEBAAEAHXZ
   |     public: int & __cdecl GMLIB::Event::LevelEvent::WeatherUpdateBeforeEvent::getRainLevel(void) const
   |---- ?getPosition@ItemActorSpawnAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAVVec3@@XZ
   |     public: class Vec3 & __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnAfterEvent::getPosition(void) const
   |---- ?getScore@GMLIB_Scoreboard@@QEAA?AV?$optional@H@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@UActorUniqueID@@_N@Z
   |     public: class std::optional<int> __cdecl GMLIB_Scoreboard::getScore(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, struct ActorUniqueID, bool)
   |---- ?resetScore@GMLIB_Scoreboard@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
   |     public: bool __cdecl GMLIB_Scoreboard::resetScore(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>)
   |---- ?getAllPlayerUuids@GMLIB_Scoreboard@@QEAA?AV?$vector@VUUID@mce@@V?$allocator@VUUID@mce@@@std@@@std@@XZ
   |     public: class std::vector<class mce::UUID, class std::allocator<class mce::UUID>> __cdecl GMLIB_Scoreboard::getAllPlayerUuids(void)
   |---- ?clearObjectiveDisplay@GMLIB_Scoreboard@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
   |     public: void __cdecl GMLIB_Scoreboard::clearObjectiveDisplay(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>)
   |---- ?getObjectiveDisplayName@GMLIB_Scoreboard@@QEAA?AV?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z
   |     public: class std::optional<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>> __cdecl GMLIB_Scoreboard::getObjectiveDisplayName(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>)
   |---- ?setObjectiveDisplayName@GMLIB_Scoreboard@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z
   |     public: bool __cdecl GMLIB_Scoreboard::setObjectiveDisplayName(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>)
   |---- ?getBlockSource@ItemActorSpawnAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAVBlockSource@@XZ
   |     public: class BlockSource & __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnAfterEvent::getBlockSource(void) const
   |---- ?getItem@ItemActorSpawnAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAVItemStack@@XZ
   |     public: class ItemStack & __cdecl GMLIB::Event::EntityEvent::ItemActorSpawnAfterEvent::getItem(void) const
   |---- ?registerBrewingMixRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00VRecipeIngredient@@@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerBrewingMixRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class RecipeIngredient)
   |---- ?getSource@MobHurtAfterEvent@EntityEvent@Event@GMLIB@@QEBAAEAVActorDamageSource@@XZ
   |     public: class ActorDamageSource & __cdecl GMLIB::Event::EntityEvent::MobHurtAfterEvent::getSource(void) const
   |---- ?getItemActor@MobPickupItemBeforeEvent@EntityEvent@Event@GMLIB@@QEBAAEAVItemActor@@XZ
   |     public: class ItemActor & __cdecl GMLIB::Event::EntityEvent::MobPickupItemBeforeEvent::getItemActor(void) const
   |---- ?registerBrewingContainerRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VRecipeIngredient@@11V?$variant@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@2@@5@@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerBrewingContainerRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class RecipeIngredient, class RecipeIngredient, class RecipeIngredient, class std::variant<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>>)
   |---- ?getLightningLevel@WeatherUpdateBeforeEvent@LevelEvent@Event@GMLIB@@QEBAAEAHXZ
   |     public: int & __cdecl GMLIB::Event::LevelEvent::WeatherUpdateBeforeEvent::getLightningLevel(void) const
   |---- ?registerSmithingTransformRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0000@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerSmithingTransformRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>)
   |---- ?registerSmithingTrimRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@000@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerSmithingTrimRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>)
   |---- ?registerStoneCutterRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VRecipeIngredient@@1V?$variant@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@2@@5@H@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerStoneCutterRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class RecipeIngredient, class RecipeIngredient, class std::variant<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>>, int)
   |---- ?registerShapelessCraftingTableRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@5@VRecipeIngredient@@V?$variant@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@2@@5@H@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerShapelessCraftingTableRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>, class RecipeIngredient, class std::variant<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>>, int)
   |---- ?registerShapedCraftingTableRecipe@JsonRecipe@Mod@GMLIB@@SA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@5@VRecipeIngredient@@V?$variant@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@VRecipeIngredient@@V?$allocator@VRecipeIngredient@@@std@@@2@@5@H@Z
   |     public: static bool __cdecl GMLIB::Mod::JsonRecipe::registerShapedCraftingTableRecipe(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::allocator<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>, class RecipeIngredient, class std::variant<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::vector<class RecipeIngredient, class std::allocator<class RecipeIngredient>>>, int)

01:33:18.823 ERROR [LeviLamina] GMLIB-LegacyRemoteCallApi 加载失败
01:33:19.000 INFO [legacy-script-engine-quickjs] loading...
01:33:19.012 INFO [legacy-script-engine-quickjs] Discovering legacy plugins...
01:33:19.012 INFO [legacy-script-engine-quickjs] No legacy plugin found, skipping migration
01:33:19.607 INFO [legacy-script-engine-quickjs] loaded
01:33:19.608 INFO [LeviLamina] legacy-script-engine-quickjs 已加载
01:33:20.813 INFO [legacy-script-engine-nodejs] loading...
01:33:20.820 INFO [legacy-script-engine-nodejs] Discovering legacy plugins...
01:33:20.820 INFO [legacy-script-engine-nodejs] No legacy plugin found, skipping migration
01:33:20.925 INFO [legacy-script-engine-nodejs] loaded
01:33:20.925 INFO [LeviLamina] legacy-script-engine-nodejs 已加载
01:33:21.041 INFO [legacy-script-engine-lua] loading...
01:33:21.055 INFO [legacy-script-engine-lua] Discovering legacy plugins...
01:33:21.055 INFO [legacy-script-engine-lua] No legacy plugin found, skipping migration
01:33:21.166 INFO [legacy-script-engine-lua] loaded
01:33:21.166 INFO [LeviLamina] legacy-script-engine-lua 已加载
01:33:21.166 INFO [legacy-script-engine-quickjs] loading plugin EQ_ChatHook
01:33:21.412 INFO [LeviLamina] EQ_ChatHook 已加载
01:33:21.412 INFO [legacy-script-engine-quickjs] loading plugin eqbase64encode
01:33:21.428 INFO [LeviLamina] eqbase64encode 已加载
01:33:21.428 INFO [legacy-script-engine-quickjs] loading plugin MoreRe
   _____                  __   ____       _     __          ___
  / ___/____  ____ ______/ /__/ __ )_____(_)___/ /___ ____ |__ \
  \__ \/ __ \/ __ `/ ___/ //_/ __  / ___/ / __  / __ `/ _ \__/ /
 ___/ / /_/ / /_/ / /  / ,< / /_/ / /  / / /_/ / /_/ /  __/ __/
/____/ .___/\__,_/_/  /_/|_/_____/_/  /_/\__,_/\__, /\___/____/
    /_/                                       /____/
2024-04-01 1:33:23 [sparkbridge2] [info] SparkBridge载入中...VERSION:1.0.2
cipes
01:33:21.452 ERROR [legacy-script-engine-quickjs] Fail to import! Function [GMLIB_API::isVersionMatched] has not been exported!
01:33:21.452 ERROR [legacy-script-engine-quickjs] In plugin <MoreRecipes>
01:33:21.453 ERROR [MoreRecipes] 无法正常加载！GMLIB-LegacyRemoteCallApi 版本过低！
01:33:21.453 ERROR [MoreRecipes] 本插件需要 GMLIB-LegacyRemoteCallApi 版本 0.8.4 以上！
01:33:21.453 INFO [LeviLamina] MoreRecipes 已加载
01:33:21.453 INFO [legacy-script-engine-nodejs] loading plugin CALL
01:33:21.818 ERROR [legacy-script-engine-nodejs] Failed to load plugin CALL: failed to load plugin code
01:33:21.818 INFO [LeviLamina] CALL 已加载
01:33:21.819 INFO [legacy-script-engine-nodejs] loading plugin sparkbridge2
01:33:23.059 INFO [LeviLamina] sparkbridge2 已加载
01:33:23.144 INFO [LeviLamina] 已加载 13 个插件
01:33:23.163 INFO [Server] setting up server logging...
01:33:23.163 INFO [Server] Starting Server
01:33:23.163 INFO [Server] Version: 1.20.62.02(ProtocolVersion 649) with LeviLamina-0.9.3+890cb5c2b
01:33:23.163 INFO [Server] Session ID: eff86cf2-8b6e-4bcb-b82e-54e46ea1e813
01:33:23.163 INFO [Server] Build ID: 22010389
01:33:23.163 INFO [Server] Branch: r/20_u6
01:33:23.163 INFO [Server] Commit ID: ecfbe634e2e231921b3c799f34169d1dcaf5bd74
01:33:23.163 INFO [Server] Configuration: Publish
01:33:23.169 INFO [Server] Level Name: Bedrock level
01:33:23.181 INFO [Server] No CDN config file found for dedicated server
01:33:23.181 INFO [Server] Game mode: 0 Survival
01:33:23.181 INFO [Server] Difficulty: 1 EASY
01:33:23.182 INFO [Server] Content logging to console is enabled.
01:33:26.268 INFO [Server] Opening level 'worlds/Bedrock level/db'
01:33:34.004 INFO [Server] IPv4 supported, port: 19132: Used for gameplay and LAN discovery
01:33:34.004 INFO [Server] IPv6 supported, port: 19133: Used for gameplay
01:33:34.139 INFO [Server] Server started in (42.8s)! For help, type "help" or "?"
01:33:34.140 INFO [Server] ================ TELEMETRY MESSAGE ===================
01:33:34.140 INFO [Server] Server Telemetry is currently not enabled.
01:33:34.140 INFO [Server] Enabling this telemetry helps us improve the game.
01:33:34.140 INFO [Server]
01:33:34.140 INFO [Server] To enable this feature, add the line 'emit-server-telemetry=true'
01:33:34.140 INFO [Server] to the server.properties file in the handheld/src-server directory
01:33:34.140 INFO [Server] ======================================================
01:33:35.846 INFO [DeathMessages] DeathMessages Loaded!
01:33:35.847 INFO [DeathMessages] Author: GroupMountain
01:33:35.847 INFO [DeathMessages] Repository: https://github.com/GroupMountain/DeathMessages
01:33:35.847 INFO [legacy-script-engine-quickjs] enabling...
01:33:35.859 INFO [legacy-script-engine-quickjs] enabled
01:33:35.859 INFO [legacy-script-engine-nodejs] enabling...
01:33:35.859 INFO [legacy-script-engine-nodejs] enabled
01:33:35.859 INFO [legacy-script-engine-lua] enabling...
01:33:35.862 INFO [legacy-script-engine-lua] enabled
01:33:35.862 ERROR [LeviLamina] CALL 启用失败
01:33:35.862 INFO [LeviLamina] 12 个插件在 (1.7秒) 内启用
01:33:36.241 ERROR [Server] 没有与选择器匹配的目标
01:33:36.242 ERROR [legacy-script-engine-quickjs] Fail to import! Function [GMLib_ModAPI::registerShapedRecipe] has not been exported!
01:33:36.242 ERROR [legacy-script-engine-quickjs] In plugin <MoreRecipes>
01:33:36.242 ERROR [legacy-script-engine-quickjs] Fail to import! Function [GMLib_ModAPI::registerShapelessRecipe] has not been exported!
01:33:36.242 ERROR [legacy-script-engine-quickjs] In plugin <MoreRecipes>
01:33:36.242 ERROR [legacy-script-engine-quickjs] Fail to import! Function [GMLib_ModAPI::registerFurnaceRecipe] has not been exported!
01:33:36.242 ERROR [legacy-script-engine-quickjs] In plugin <MoreRecipes>
01:33:36.242 ERROR [legacy-script-engine-quickjs] Fail to import! Function [GMLib_ModAPI::registerBrewingMixRecipe] has not been exported!
01:33:36.242 ERROR [legacy-script-engine-quickjs] In plugin <MoreRecipes>
01:33:36.242 ERROR [legacy-script-engine-quickjs] Fail to import! Function [GMLib_ModAPI::registerStoneCutterRecipe] has not been exported!
01:33:36.242 ERROR [legacy-script-engine-quickjs] In plugin <MoreRecipes>
01:33:36.242 INFO [MoreRecipes] MoreRecipes 已加载！
2024-04-01 1:33:36 [sparkbridge2] [info] 检测到了7个插件
2024-04-01 1:33:36 [sparkbridge2] [info] loading bridgebase
2024-04-01 1:33:36 [sparkbridge2] [info] loading economy
2024-04-01 1:33:36 [sparkbridge2] [info] loading JandLandCmsg
2024-04-01 1:33:36 [sparkbridge2] [info] loading llapi
2024-04-01 1:33:36 [sparkbridge2] [info] loading mc
2024-04-01 1:33:36 [sparkbridge2] [info] loading regex
2024-04-01 1:33:36 [sparkbridge2] [info] 开始加载插件
2024-04-01 1:33:36 [sparkbridge2] [info] 加载 bridgebase
2024-04-01 1:33:36 [sparkbridge2] [info] bridgebase 加载完成，作者：lition
2024-04-01 1:33:36 [sparkbridge2] [info] 加载 mc
2024-04-01 1:33:36 [sparkbridge2] [info] mc 加载完成，作者：lition
2024-04-01 1:33:36 [sparkbridge2] [info] 加载 regex
2024-04-01 1:33:36 [sparkbridge2] [info] regex 加载完成，作者：lition
2024-04-01 1:33:36 [sparkbridge2] [info] 加载 economy
2024-04-01 1:33:36 [sparkbridge2] [info] economy 加载完成，作者：lition
2024-04-01 1:33:36 [sparkbridge2] [info] 加载 JandLandCmsg
2024-04-01 1:33:36 [sparkbridge2] [info] JandLandCmsg 加载完成，作者：lition
2024-04-01 1:33:36 [sparkbridge2] [info] 加载 llapi
2024-04-01 1:33:36 [sparkbridge2] [info] llapi 加载完成，作者：lition
2024-04-01 1:33:36 [Qadapter] [info] 登录成功，开始处理事件
01:33:45.150 INFO [Server] Server stop requested.
01:33:45.179 INFO [Server] Stopping server...
Quit correctly

**Comment by liuyuhang9066** [comment]
补充：GMLIB-LegacyRemoteCallApi版本是0.9.5

**Comment by Tsubasa6848** [comment]
> 补充：GMLIB-LegacyRemoteCallApi版本是0.9.5

如果LRCA使用0.9.5，请使用LeviLamina 0.9.5和GMLIB 0.9.8。
目前 LeviLamina 和 GMLIB 均为 Prelease阶段，每个小版本更新都可能修改API。
未来正式版不会出现此问题。
