### ISSUE TITLE
[Bug]: getPlayerNBT返回Null

### ISSUE THREAD

**Issue by Hurry1027** [GroupMountain/GMLIB-LegacyRemoteCallApi#15]
### Describe the bug

getPlayerNBT() api失效，导致相关lse插件出错。

### To Reproduce

> let g = require("./GMLIB-LegacyRemoteCallApi/lib/GMLIB_API-JS").Minecraft;
19:11:08.146 INFO [legacy-script-engine-quickjs] Null
> g.getPlayerNbt("04996ee2-5864-36c4-a7b6-d1b0dfa030de")
19:13:05.552 INFO [legacy-script-engine-quickjs] Null

### Expected behavior

正常返回nbt

### BDS Version

1.20.81

### Version

0.12.3

**Comment by Tsubasa6848** [comment]
已修复
