### ISSUE TITLE
[Bug]:  调用 BEPlaceholderAPI 的 registerPlayerPlaceholder 接口报错

### ISSUE THREAD

**Issue by BIYUEHU** [GroupMountain/GMLIB-LegacyRemoteCallApi#31]
### Describe the bug

调用  BEPlaceholderAPI 的 `registerPlayerPlaceholder` 接口产生以下报错：
```txt
Fail to import! Function [BEPlaceholderAPI::registerPlayerPlaceholder] has not been exported! 
```
![QQ截图20240717111914](https://github.com/user-attachments/assets/f796a73c-a8e4-457e-8a66-41c5015eff30)
原 GMLIB-LegacyRemoteCallApi 版本 `0.12.5` 使用正常，更新至 `0.13.0` 后报错

### To Reproduce

控制台输入 ` jsdebug require('./GMLIB-LegacyRemoteCallApi/lib/BEPlaceholderAPI-JS.js').PAPI.registerPlayerPlaceholder(function getName(pl){ return pl.realName},'plugin', 'name' )` 

### Expected behavior

修复该 bug

### Screenshots

![QQ截图20240717111914](https://github.com/user-attachments/assets/5cebf169-6dcc-43bb-b99a-1af0829121c4)

### Platform

Windows 11

### BDS Version

1.21.0-3.685+158de25

### LeviLamina Version

LeviLamina-0.13.1+123135e8e

### Version

0.13.0

**Comment by KobeBryant114514** [comment]
插件的manifest.json是否写了依赖项？
从0.13.0开始，GMLIB-LegacyRemoteCallApi需要被依赖后才会加载，否则默认不加载。
请在调用接口的插件的manifest.json里面写上依赖或者可选依赖
