### ISSUE TITLE
标题：漏洞反馈 GMLIB-LRCA删除玩家nbtAPI删除到了空指针导致崩服

### ISSUE THREAD

**Issue by Atrium4641** [GroupMountain/GMLIB-LegacyRemoteCallApi#35]
### 简述漏洞

let deleteNBT = ll.imports("GMLIB_API", "deletePlayerNbt"); // GMLIB-LRCA 删除玩家nbt API删到空指针导致崩服

GMLIB-LRCA删除玩家nbtAPI删除到了空指针导致崩服

### 复现方案

let deleteNBT = ll.imports("GMLIB_API", "deletePlayerNbt"); // GMLIB-LRCA 删除玩家nbt API删到空指针导致崩服

GMLIB-LRCA删除玩家nbtAPI删除到了空指针导致崩服

### 预期结果

不崩服

### 日志或截图

[crash.zip](https://github.com/user-attachments/files/17300703/crash.zip)

_No response_

### 操作系统

Win10

### BDS 版本

1.21.3

### LeviLamina 版本

1.13.5

_No response_

### GMLIB 版本

0.13.5

_No response_

**Comment by KobeBryant114514** [comment]
无法复现，请提供插件环境

**Comment by Atrium4641** [comment]
> 无法复现，请提供插件环境

你试试删除一个从未进过服的玩家的名字试试

**Comment by Atrium4641** [comment]
![image](https://github.com/user-attachments/assets/1428f4bf-1932-43e4-af8b-35888bb498ae)

**Comment by KobeBryant114514** [comment]
首先此API传入参数应该是玩家uuid

此外我输入任意字符串依旧无法复现
![image](https://github.com/user-attachments/assets/f865cc36-5e2d-476c-b53f-672fec313b19)

**Comment by Atrium4641** [comment]
> 首先此API传入参数应该是玩家uuid
> 
> 此外我输入任意字符串依旧无法复现 ![image](https://private-user-images.githubusercontent.com/116721335/374784841-f865cc36-5e2d-476c-b53f-672fec313b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDI4MjcsIm5iZiI6MTcyODQ0MjUyNywicGF0aCI6Ii8xMTY3MjEzMzUvMzc0Nzg0ODQxLWY4NjVjYzM2LTVlMmQtNDc2Yy1iNTNmLTY3MmZlYzMxM2IxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwMjU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODVmNzc0YjZlNjQ0ZjYzMzg0ZjY2MThiNjVmZWUwYTJhYWYzYmRlOThmNTM3OTA4YjhmOTFjZmJlOTk4NTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V3sqkuctAjEIc4AjMVG_o44laECjIh1M6NiM60vGTfQ)

没事了，用错API了，我用的是mc.deletePlayerNbt() 应该是LL的问题了，关了吧
